duwamish_flavor_data:
  # image: lukeswart/smartercleanup-flavors-data:django-1.9
  image: smartercleanup/platform-data:django-1.9
  volumes:
    - /$DUWAMISH_DEV_FLAVOR
  environment:
    - FLAVOR=${DUWAMISH_DEV_FLAVOR}
    - SITE_KEY=${DUWAMISH_DEV_KEY}
    - SITE_URL=${DUWAMISH_DEV_URL}
  command: sh -c "git fetch --tags && git checkout lukeswart/develop && /platform/start-data-container.sh"
  # command: sh -c "git fetch && git checkout lukeswart/placetype-style-refactor-test && git pull --rebase && /duwamish/start-data-container.sh"

duwamish_flavor:
  # image: lukeswart/smartercleanup-flavors:django-1.9
  image: smartercleanup/platform:django-1.9
  ports:
    - "${DUWAMISH_DEV_PORT}:${DUWAMISH_DEV_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${DUWAMISH_DEV_PORT}
    - FLAVOR=${DUWAMISH_DEV_FLAVOR}
    - SITE_KEY=${DUWAMISH_DEV_KEY}
    - SITE_URL=${DUWAMISH_DEV_URL}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always
  command: sh -c "git fetch --tags && git checkout lukeswart/develop && /platform/start.sh"
  # command: sh -c "git fetch && git checkout lukeswart/placetype-style-refactor-test && git pull --rebase && /duwamish/start.sh"

air_data:
  image: smartercleanup/flavors-data
  volumes:
    - /$AIR_FLAVOR
  environment:
    - FLAVOR=$AIR_FLAVOR
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}

air:
  image: smartercleanup/flavors
  ports:
    - "${AIR_PORT}:${AIR_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${AIR_PORT}
    - FLAVOR=${AIR_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}
    - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always

waterfront_data:
  image: smartercleanup/flavors-data:release-0.6.1
  volumes:
    - /${GT_WATERFRONT_FLAVOR}
  environment:
    - FLAVOR=${GT_WATERFRONT_FLAVOR}
    - SITE_KEY=${GT_WATERFRONT_KEY}
    - SITE_URL=${GT_WATERFRONT_URL}
  command: sh -c "git fetch && git checkout futuresoup/updates && /duwamish/start-data-container.sh"

waterfront:
  image: smartercleanup/flavors:release-0.6.1
  ports:
    - "${GT_WATERFRONT_PORT}:${GT_WATERFRONT_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${GT_WATERFRONT_PORT}
    - FLAVOR=${GT_WATERFRONT_FLAVOR}
    - SITE_KEY=${GT_WATERFRONT_KEY}
    - SITE_URL=${GT_WATERFRONT_URL}
    - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  command: sh -c "git fetch && git checkout futuresoup/updates && /duwamish/start.sh"
  restart: always

# georgetowngreen_data:
#   image: smartercleanup/flavors-data
#   volumes:
#     - /${GT_WATERFRONT_FLAVOR}
#   environment:
#     - FLAVOR=${GEORGETOWNGREEN_FLAVOR}
#     - SITE_KEY=${GEORGETOWNGREEN_KEY}
#     - SITE_URL=${GEORGETOWNGREEN_URL}
# 
# georgetowngreen:
#   image: smartercleanup/flavors
#   ports:
#     - "${GEORGETOWNGREEN_PORT}:${GEORGETOWNGREEN_PORT}"
#   environment:
#     - DEBUG=${DEBUG}
#     - PORT=${GEORGETOWNGREEN_PORT}
#     - FLAVOR=${GEORGETOWNGREEN_FLAVOR}
#     - SITE_KEY=${GEORGETOWNGREEN_KEY}
#     - SITE_URL=${GEORGETOWNGREEN_URL}
#     - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
#     # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
#   restart: always

nginx_flavors:
  image: smartercleanup/flavors-nginx
  links:
    - "${DUWAMISH_DEV_FLAVOR}"
    - "${AIR_FLAVOR}"
    - "${GT_WATERFRONT_FLAVOR}"
  volumes_from:
    - "${DUWAMISH_DEV_FLAVOR}_data"
    - "${AIR_FLAVOR}_data"
    - "${GT_WATERFRONT_FLAVOR}_data"
  ports:
    - "80:80"
  volumes:
    - "./dev-air-georgetowngreen_nginx.conf:/nginx.conf"
  restart: always
