duwamish_flavor_data:
  image: smartercleanup/platform-data:release-0.6.3
  volumes:
    - /$DUWAMISH_DEV_FLAVOR
  environment:
    - FLAVOR=${DUWAMISH_DEV_FLAVOR}
    - SITE_KEY=${DUWAMISH_DEV_KEY}
    - SITE_URL=${DUWAMISH_DEV_URL}
  command: sh -c "git fetch && git checkout lukeswart/develop && git pull --rebase && /platform/start-data-container.sh"
  # command: sh -c "git fetch && git checkout lukeswart/develop && git pull --rebase && /duwamish/start-data-container.sh"

duwamish_flavor:
  image: smartercleanup/platform:release-0.6.3
  ports:
    - "${DUWAMISH_DEV_PORT}:${DUWAMISH_DEV_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${DUWAMISH_DEV_PORT}
    - FLAVOR=${DUWAMISH_DEV_FLAVOR}
    - SITE_KEY=${DUWAMISH_DEV_KEY}
    - SITE_URL=${DUWAMISH_DEV_URL}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always
  # command: sh -c "git fetch --tags && git checkout lukeswart/develop && /platform/start.sh"
  command: sh -c "git fetch && git checkout lukeswart/develop && git pull --rebase && /platform/start.sh"

air_data:
  image: smartercleanup/platform-data:release-0.6.3
  volumes:
    - /$AIR_FLAVOR
  environment:
    - FLAVOR=$AIR_FLAVOR
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}

air:
  image: smartercleanup/platform:release-0.6.3
  ports:
    - "${AIR_PORT}:${AIR_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${AIR_PORT}
    - FLAVOR=${AIR_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}
    - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always

trees_data:
  image: smartercleanup/platform-data:release-0.6.3
  volumes:
    - /${TREES_FLAVOR}
  environment:
    - FLAVOR=${TREES_FLAVOR}
    - SITE_KEY=${TREES_KEY}
    - SITE_URL=${TREES_URL}
  command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

trees:
  image: smartercleanup/platform:release-0.6.3
  ports:
    - "${TREES_PORT}:${TREES_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${TREES_PORT}
    - FLAVOR=${TREES_FLAVOR}
    - SITE_KEY=${TREES_KEY}
    - SITE_URL=${TREES_URL}
    # - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"
  restart: always

# georgetowngreen_data:
#   image: smartercleanup/flavors-data
#   volumes:
#     - /${GT_WATERFRONT_FLAVOR}
#   environment:
#     - FLAVOR=${GEORGETOWNGREEN_FLAVOR}
#     - SITE_KEY=${GEORGETOWNGREEN_KEY}
#     - SITE_URL=${GEORGETOWNGREEN_URL}
#
# georgetowngreen:
#   image: smartercleanup/flavors
#   ports:
#     - "${GEORGETOWNGREEN_PORT}:${GEORGETOWNGREEN_PORT}"
#   environment:
#     - DEBUG=${DEBUG}
#     - PORT=${GEORGETOWNGREEN_PORT}
#     - FLAVOR=${GEORGETOWNGREEN_FLAVOR}
#     - SITE_KEY=${GEORGETOWNGREEN_KEY}
#     - SITE_URL=${GEORGETOWNGREEN_URL}
#     - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
#     # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
#   restart: always

nginx_flavors:
  image: lukeswart/nginx-openresty:release-1.9.7.3
  links:
    - "${DUWAMISH_DEV_FLAVOR}"
    - "${AIR_FLAVOR}"
    - "${TREES_FLAVOR}"
  volumes_from:
    - "${DUWAMISH_DEV_FLAVOR}_data"
    - "${AIR_FLAVOR}_data"
    - "${TREES_FLAVOR}_data"
  ports:
    - "80:80"
  volumes:
    - "./dev-air-trees_nginx.conf:/nginx.conf"
  restart: always
