version: '2'
services:
  # docker-compose up -f base-compose.yml  -f duwamish-compose.yml -f willamette-compose.yml
  duwamish:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish_flavor
      - SITE_KEY=${DUWAMISH_DEV_KEY}
      - SITE_URL=${DUWAMISH_DEV_URL}
      # - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
      # Multi-dataset configs:
      # - DUWAMISH_DATASET_KEY=${DUWAMISH_DEV_KEY}
      # - DUWAMISH_SITE_URL=${DUWAMISH_DEV_URL}
      # - TREES_DATASET_KEY=${TREES_DEV_KEY}
      # - TREES_SITE_URL=${TREES_DEV_URL}
      # - AIR_DATASET_KEY=${AIR_DEV_KEY}
      # - AIR_SITE_URL=${AIR_DEV_URL}
    restart: always
    # command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  duwamish_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /duwamish_production
    environment:
      - CONTAINER=duwamish_production
      # - FLAVOR=duwamish_flavor
      # # This should be a unique name for every container, for mounting purposes
      # - SITE_KEY=${DUWAMISH_DEV_KEY}
      # - SITE_URL=${DUWAMISH_DEV_URL}
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"
    # command: sh -c "git checkout master && /platform/start-data-container.sh"

  # bogtobay
  bogtobay:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=bogtobay
      - SITE_KEY=${BOGTOBAY_KEY}
      - SITE_URL=${BOGTOBAY_URL}
      - BOGTOBAY_DATASET_KEY=${BOGTOBAY_KEY}
      - BOGTOBAY_SITE_URL=${BOGTOBAY_URL}
      # - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
      # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    restart: always
    # command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"
    command: sh -c "git fetch && git checkout data-container-updates && git pull --rebase && /platform/start.sh"

  bogtobay_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /bogtobay
    environment:
      - CONTAINER=bogtobay
      # - FLAVOR=bogtobay
      # - SITE_KEY=${BOGTOBAY_KEY}
      # - SITE_URL=${BOGTOBAY_URL}
    command: sh -c "git fetch && git checkout data-container-updates && git pull --rebase && /platform/start-data-container.sh"

  trees:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=trees
      - SITE_KEY=${TREES_KEY}
      - SITE_URL=${TREES_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  trees_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /trees
    environment:
      - CONTAINER=trees
      # - FLAVOR=trees
      # - SITE_KEY=${TREES_KEY}
      # - SITE_URL=${TREES_URL}
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  snoqualmie:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=snoqualmie
      - SITE_KEY=${SNOQUALMIE_KEY}
      - SITE_URL=${SNOQUALMIE_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  snoqualmie_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /snoqualmie
    environment:
      - CONTAINER=snoqualmie
      # - FLAVOR=snoqualmie
      # - SITE_KEY=${SNOQUALMIE_KEY}
      # - SITE_URL=${SNOQUALMIE_URL}
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  willamette:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=willamette
      - SITE_KEY=${WILLAMETTE_KEY}
      - SITE_URL=${WILLAMETTE_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  willamette_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /willamette
    environment:
      - CONTAINER=willamette
      # - FLAVOR=willamette
      # - SITE_KEY=${WILLAMETTE_KEY}
      # - SITE_URL=${WILLAMETTE_URL}
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  lakewashington:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=lakewashington
      - SITE_KEY=${LAKEWASHINGTON_KEY}
      - SITE_URL=${LAKEWASHINGTON_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  lakewashington_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /lakewashington
    environment:
      - CONTAINER=lakewashington
      # - FLAVOR=lakewashington
      # - SITE_KEY=${LAKEWASHINGTON_KEY}
      # - SITE_URL=${LAKEWASHINGTON_URL}
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  waterfront:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=waterfront
      - SITE_KEY=${WATERFRONT_KEY}
      - SITE_URL=${WATERFRONT_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  waterfront_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /waterfront
    environment:
      - CONTAINER=waterfront
      # - FLAVOR=lakewashington
      # - SITE_KEY=${LAKEWASHINGTON_KEY}
      # - SITE_URL=${LAKEWASHINGTON_URL}
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  gtopenspace:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=gtopenspace
      - SITE_KEY=${GTOPENSPACE_KEY}
      - SITE_URL=${GTOPENSPACE_URL}
    restart: always
    command: sh -c "git fetch && git checkout gtopenspace && git pull --rebase && /platform/start.sh"

  gtopenspace_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /gtopenspace
    environment:
      - CONTAINER=gtopenspace
      # - FLAVOR=lakewashington
      # - SITE_KEY=${LAKEWASHINGTON_KEY}
      # - SITE_URL=${LAKEWASHINGTON_URL}
    command: sh -c "git fetch && git checkout gtopenspace && git pull --rebase && /platform/start-data-container.sh"

  watershed:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish-watershed
      - SITE_KEY=${DUWAMISH_KEY}
      - SITE_URL=${DUWAMISH_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  watershed_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /watershed
    environment:
      - CONTAINER=watershed
      # - FLAVOR=lakewashington
      # - SITE_KEY=${LAKEWASHINGTON_KEY}
      # - SITE_URL=${LAKEWASHINGTON_URL}
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"
