version: '2'
services:
  duwamish:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish_flavor
      - SITE_KEY=${DUWAMISH_KEY}
      - SITE_URL=${DUWAMISH_URL}
      - DUWAMISH_DATASET_KEY=${DUWAMISH_KEY}
      - DUWAMISH_SITE_URL=${DUWAMISH_URL}
      - DUWAMISHFEATURED_DATASET_KEY=${DUWAMISHFEATURED_KEY}
      - DUWAMISHFEATURED_SITE_URL=${DUWAMISHFEATURED_URL}
      - TREES_DATASET_KEY=${TREES_KEY}
      - TREES_SITE_URL=${TREES_URL}
      # TODO: Set up AIR production datasets!
      - AIR_DATASET_KEY=${AIR_DEV_KEY}
      - AIR_SITE_URL=${AIR_DEV_URL}
      - RESTORATION_DATASET_KEY=${RESTORATION_KEY}
      - RESTORATION_SITE_URL=${RESTORATION_URL}
      - VISION_DATASET_KEY=${VISION_KEY}
      - VISION_SITE_URL=${VISION_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  duwamish_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /duwamish_production
    environment:
      - FLAVOR=duwamish_flavor
      - CONTAINER=duwamish_production
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  duwamish-dev:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish_flavor
      - SITE_KEY=${DUWAMISH_DEV_KEY}
      - SITE_URL=${DUWAMISH_DEV_URL}
      # Multi-dataset configs:
      - DUWAMISH_DATASET_KEY=${DUWAMISH_DEV_KEY}
      - DUWAMISH_SITE_URL=${DUWAMISH_DEV_URL}
      - TREES_DATASET_KEY=${TREES_DEV_KEY}
      - TREES_SITE_URL=${TREES_DEV_URL}
      - AIR_DATASET_KEY=${AIR_DEV_KEY}
      - AIR_SITE_URL=${AIR_DEV_URL}
      - VISION_DATASET_KEY=${VISION_DEV_KEY}
      - VISION_SITE_URL=${VISION_DEV_URL}
      - RESTORATION_DATASET_KEY=${RESTORATION_DEV_KEY}
      - RESTORATION_SITE_URL=${RESTORATION_DEV_URL}
      - EMAIL_DEBUG=False
      - EMAIL_USE_TLS=True
      - EMAIL_ADDRESS=${DEV_EMAIL_ADDRESS}
      - EMAIL_USERNAME=${DEV_EMAIL_PASSWORD}
      - EMAIL_PASSWORD=${DEV_EMAIL_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_NOTIFICATIONS_BCC=${EMAIL_NOTIFICATIONS_BCC}
    restart: always
    command: sh -c "git fetch && git checkout browserEditor-401 && git pull --rebase && /platform/scripts/start.sh"

  duwamish-dev_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /duwamish_dev
    environment:
      - FLAVOR=duwamish_flavor
      - CONTAINER=duwamish_dev
    command: sh -c "git fetch && git checkout browserEditor-401 && git pull --rebase && /platform/scripts/start-data-container.sh"

  duwamish-dev2:
    image: mapseed/platform:release-0.8.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish_flavor
      - SITE_KEY=${DUWAMISH_DEV_KEY}
      - SITE_URL=${DUWAMISH_DEV_URL}
      - DUWAMISH_DATASET_KEY=${DUWAMISH_DEV_KEY}
      - DUWAMISH_SITE_URL=${DUWAMISH_DEV_URL}
      - TREES_DATASET_KEY=${TREES_DEV_KEY}
      - TREES_SITE_URL=${TREES_DEV_URL}
      # TODO: Set up AIR production datasets!
      - AIR_DATASET_KEY=${AIR_DEV_KEY}
      - AIR_SITE_URL=${AIR_DEV_URL}
      - RESTORATION_DATASET_KEY=${RESTORATION_DEV_KEY}
      - RESTORATION_SITE_URL=${RESTORATION_DEV_URL}
      - VISION_DATASET_KEY=${VISION_DEV_KEY}
      - VISION_SITE_URL=${VISION_DEV_URL}
    restart: always
    command: sh -c "git fetch && git checkout sidebar-561 && git pull --rebase && /platform/scripts/start.sh"

  duwamish-dev2_data:
    image: mapseed/platform-data:release-0.8.1
    volumes:
      - /duwamish_dev2
    environment:
      - FLAVOR=duwamish_flavor
      - CONTAINER=duwamish_dev2
    command: sh -c "git fetch && git checkout sidebar-561 && git pull --rebase && /platform/scripts/start-data-container.sh"

  bogtobay:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=bogtobay
      - SITE_KEY=${BOGTOBAY_KEY}
      - SITE_URL=${BOGTOBAY_URL}
      - BOGTOBAY_DATASET_KEY=${BOGTOBAY_KEY}
      - BOGTOBAY_SITE_URL=${BOGTOBAY_URL}
      # - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
      # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  bogtobay_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /bogtobay
    environment:
      - FLAVOR=bogtobay
      - CONTAINER=bogtobay
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  trees:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=trees
      - SITE_KEY=${TREES_KEY}
      - SITE_URL=${TREES_URL}
    restart: always
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start.sh"

  trees_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /trees
    environment:
      - FLAVOR=trees
      - CONTAINER=trees
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start-data-container.sh"

  snoqualmie:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=snoqualmie
      - SITE_KEY=${SNOQUALMIE_KEY}
      - SITE_URL=${SNOQUALMIE_URL}
    restart: always
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start.sh"

  snoqualmie_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /snoqualmie
    environment:
      - FLAVOR=snoqualmie
      - CONTAINER=snoqualmie
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start-data-container.sh"

  willamette:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=willamette
      - SITE_KEY=${WILLAMETTE_KEY}
      - SITE_URL=${WILLAMETTE_URL}
    restart: always
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start.sh"

  willamette_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /willamette
    environment:
      - FLAVOR=willamette
      - CONTAINER=willamette
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start-data-container.sh"

  lakewashington:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=lakewashington
      - SITE_KEY=${LAKEWASHINGTON_KEY}
      - SITE_URL=${LAKEWASHINGTON_URL}
      - LAKEWASHINGTON_DATASET_KEY=${LAKEWASHINGTON_KEY}
      - LAKEWASHINGTON_SITE_URL=${LAKEWASHINGTON_URL}
      - LAKEWASHINGTONFEATURED_DATASET_KEY=${LAKEWASHINGTONFEATURED_KEY}
      - LAKEWASHINGTONFEATURED_SITE_URL=${LAKEWASHINGTONFEATURED_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  lakewashington_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /lakewashington
    environment:
      - FLAVOR=lakewashington
      - CONTAINER=lakewashington
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  waterfront:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=waterfront
      - SITE_KEY=${WATERFRONT_KEY}
      - SITE_URL=${WATERFRONT_URL}
    restart: always
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start.sh"

  waterfront_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /waterfront
    environment:
      - FLAVOR=waterfront
      - CONTAINER=waterfront
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start-data-container.sh"

  gtopenspace:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=gtopenspace
      - SITE_KEY=${GTOPENSPACE1_KEY}
      - SITE_URL=${GTOPENSPACE1_URL}
      - GTOPENSPACE1_DATASET_KEY=${GTOPENSPACE1_KEY}
      - GTOPENSPACE1_SITE_URL=${GTOPENSPACE1_URL}
      - GTOPENSPACE2_DATASET_KEY=${GTOPENSPACE2_KEY}
      - GTOPENSPACE2_SITE_URL=${GTOPENSPACE2_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  gtopenspace_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /gtopenspace
    environment:
      - SITE_KEY=${GTOPENSPACE1_KEY}
      - SITE_URL=${GTOPENSPACE1_URL}
      - FLAVOR=gtopenspace
      - CONTAINER=gtopenspace
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  watershed:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish-watershed
      - SITE_KEY=${DUWAMISH_KEY}
      - SITE_URL=${DUWAMISH_URL}
    restart: always
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start.sh"

  watershed_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /watershed
    environment:
      - FLAVOR=duwamish-watershed
      - CONTAINER=watershed
    command: sh -c "git fetch && git checkout 0.6.4 && /platform/start-data-container.sh"

  greenways:
    image: smartercleanup/platform:release-0.7.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=greenways
      - SITE_KEY=${GREENWAYS_KEY}
      - SITE_URL=${GREENWAYS_URL}
      # Multi-dataset configs:
      - GREENWAYS_DATASET_KEY=${GREENWAYS_KEY}
      - GREENWAYS_SITE_URL=${GREENWAYS_URL}
    restart: always
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"

  greenways_data:
    image: smartercleanup/platform-data:release-0.7.2
    volumes:
      - /greenways
    environment:
      - FLAVOR=greenways
      - CONTAINER=greenways
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start-data-container.sh"

  rail:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=rail
      - SITE_KEY=${RAIL_KEY}
      - SITE_URL=${RAIL_URL}
      # Multi-dataset configs:
      - RAIL_DATASET_KEY=${RAIL_KEY}
      - RAIL_SITE_URL=${RAIL_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  rail_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /rail
    environment:
      - FLAVOR=rail
      - CONTAINER=rail
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  pugetsound:
    image: mapseed/platform:release-0.8.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=pugetsound
      - SITE_KEY=${PUGETSOUND_DEV_KEY}
      - SITE_URL=${PUGETSOUND_DEV_URL}
      # Multi-dataset configs:
      - DUWAMISH_DATASET_KEY=${DUWAMISH_KEY}
      - DUWAMISH_SITE_URL=${DUWAMISH_URL}
      - PUGETSOUND_SITE_URL=${PUGETSOUND_DEV_URL}
      - PUGETSOUND_DATASET_KEY=${PUGETSOUND_DEV_KEY}
      - PUGETSOUNDFEATURED_SITE_URL=${PUGETSOUNDFEATURED_DEV_SITE_URL}
      - PUGETSOUNDFEATURED_DATASET_KEY=${PUGETSOUNDFEATURED_DEV_DATASET_KEY}
    restart: always
    command: sh -c "git fetch && git checkout pugetsound-dev && git pull --rebase && /platform/scripts/start.sh"

  pugetsound_data:
    image: mapseed/platform-data:release-0.8.1
    volumes:
      - /pugetsound
    environment:
      - FLAVOR=pugetsound
      - CONTAINER=pugetsound
    command: sh -c "git fetch && git checkout pugetsound-dev && git pull --rebase && /platform/scripts/start-data-container.sh"

  raingardens:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=raingardens
      - SITE_KEY=${RAINGARDENS_KEY}
      - SITE_URL=${RAINGARDENS_URL}
      - RAINGARDENS_DATASET_KEY=${RAINGARDENS_KEY}
      - RAINGARDENS_SITE_URL=${RAINGARDENS_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  raingardens_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /raingardens
    environment:
      - FLAVOR=raingardens
      - CONTAINER=raingardens
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  pboakland:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=pboakland
      - SITE_KEY=${PBOAKLAND_KEY}
      - SITE_URL=${PBOAKLAND_URL}
      - PBOAKLAND_DATASET_KEY=${PBOAKLAND_KEY}
      - PBOAKLAND_SITE_URL=${PBOAKLAND_URL}
      - EMAIL_DEBUG=False
      - EMAIL_USE_TLS=True
      - EMAIL_ADDRESS=${PBOAKLAND_EMAIL_ADDRESS}
      - EMAIL_USERNAME=${EMAIL_PASSWORD}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_NOTIFICATIONS_BCC=${EMAIL_NOTIFICATIONS_BCC}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  pboakland_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /pboakland
    environment:
      - FLAVOR=pboakland
      - CONTAINER=pboakland
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  pboakland-dev:
    image: mapseed/platform:release-0.7.5
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=pboakland
      - SITE_KEY=${PBOAKLAND_DEV_KEY}
      - SITE_URL=${PBOAKLAND_DEV_URL}
      - PBOAKLAND_DATASET_KEY=${PBOAKLAND_DEV_KEY}
      - PBOAKLAND_SITE_URL=${PBOAKLAND_DEV_URL}
      #- EMAIL_DEBUG=False
      #- EMAIL_USE_TLS=True
      #- EMAIL_ADDRESS=${PBOAKLAND_EMAIL_ADDRESS}
      #- EMAIL_USERNAME=${EMAIL_PASSWORD}
      #- EMAIL_PASSWORD=${EMAIL_PASSWORD}
      #- EMAIL_HOST=${EMAIL_HOST}
      #- EMAIL_PORT=${EMAIL_PORT}
      #- EMAIL_NOTIFICATIONS_BCC=${EMAIL_NOTIFICATIONS_BCC}
    restart: always
    command: sh -c "git fetch && git checkout story-sidebar-navigator && git pull --rebase && /platform/scripts/start.sh"

  pboakland-dev_data:
    image: mapseed/platform-data:release-0.7.5
    volumes:
      - /pboakland_dev
    environment:
      - FLAVOR=pboakland
      - CONTAINER=pboakland_dev
    command: sh -c "git fetch && git checkout story-sidebar-navigator && git pull --rebase && /platform/scripts/start-data-container.sh"

  greensboropb:
    image: mapseed/platform:release-0.8.2
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=greensboropb
      - SITE_KEY=${GREENSBOROPB_DEV_KEY}
      - SITE_URL=${GREENSBOROPB_DEV_URL}
      - GREENSBOROPB_DATASET_KEY=${GREENSBOROPB_KEY}
      - GREENSBOROPB_SITE_URL=${GREENSBOROPB_URL}
      - MAPBOX_TOKEN=${GREENSBOROPB_MAPBOX_TOKEN}
      - EMAIL_ADDRESS=${GREENSBOROPB_EMAIL_ADDRESS}
      - EMAIL_USERNAME=${EMAIL_PASSWORD}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_NOTIFICATIONS_BCC=${EMAIL_NOTIFICATIONS_BCC}
      - GREENSBOROPB_ROUND1_SITE_URL=${GREENSBOROPB_ROUND1_SITE_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  greensboropb_data:
    image: mapseed/platform-data:release-0.8.2
    volumes:
      - /greensboropb
    environment:
      - FLAVOR=greensboropb
      - CONTAINER=greensboropb
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  central-puget-sound:
    image: mapseed/platform:release-0.8.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=central-puget-sound
      - SITE_KEY=${MW_KEY}
      - SITE_URL=${MW_URL}
      - MW_DATASET_KEY=${MW_KEY}
      - MW_SITE_URL=${MW_URL}
      - MWFEATURED_DATASET_KEY=${MWFEATURED_DATASET_KEY}
      - MWFEATURED_SITE_URL=${MWFEATURED_SITE_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start.sh"

  central-puget-sound_data:
    image: mapseed/platform-data:release-0.8.1
    volumes:
      - /central-puget-sound
    environment:
      - FLAVOR=central-puget-sound
      - CONTAINER=central-puget-sound
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/scripts/start-data-container.sh"

  central-puget-sound-dev:
    image: mapseed/platform:release-0.8.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=central-puget-sound
      - SITE_KEY=${MW_KEY}
      - SITE_URL=${MW_URL}
      - MW_DATASET_KEY=${MW_KEY}
      - MW_SITE_URL=${MW_URL}
      - MWFEATURED_DATASET_KEY=${MWFEATURED_DATASET_KEY}
      - MWFEATURED_SITE_URL=${MWFEATURED_SITE_URL}
    restart: always
    command: sh -c "git fetch && git checkout cps-updates-flow-layout && git pull --rebase && /platform/scripts/start.sh"

  central-puget-sound-dev_data:
    image: mapseed/platform-data:release-0.8.1
    volumes:
      - /central-puget-sound_dev
    environment:
      - FLAVOR=central-puget-sound
      - CONTAINER=central-puget-sound_dev
    command: sh -c "git fetch && git checkout cps-updates-flow-layout && git pull --rebase && /platform/scripts/start-data-container.sh"

    
    
