version: '2'
services:
  # docker-compose up -f base-compose.yml  -f duwamish-compose.yml -f willamette-compose.yml
  duwamish:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish_flavor
      - SITE_KEY=${DUWAMISH_KEY}
      - SITE_URL=${DUWAMISH_URL}
      # - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  duwamish_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /duwamish_production
    environment:
      - CONTAINER=duwamish_production
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  duwamish-dev:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish_flavor
      - SITE_KEY=${DUWAMISH_DEV_KEY}
      - SITE_URL=${DUWAMISH_DEV_URL}
      # Multi-dataset configs:
      - DUWAMISH_DATASET_KEY=${DUWAMISH_DEV_KEY}
      - DUWAMISH_SITE_URL=${DUWAMISH_DEV_URL}
      - TREES_DATASET_KEY=${TREES_DEV_KEY}
      - TREES_SITE_URL=${TREES_DEV_URL}
      - AIR_DATASET_KEY=${AIR_DEV_KEY}
      - AIR_SITE_URL=${AIR_DEV_URL}
    restart: always
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"

  duwamish-dev_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /duwamish_dev
    environment:
      - CONTAINER=duwamish_dev
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start-data-container.sh"

  bogtobay:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=bogtobay
      - SITE_KEY=${BOGTOBAY_KEY}
      - SITE_URL=${BOGTOBAY_URL}
      - BOGTOBAY_DATASET_KEY=${BOGTOBAY_KEY}
      - BOGTOBAY_SITE_URL=${BOGTOBAY_URL}
      # - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
      # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    restart: always
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"

  bogtobay_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /bogtobay
    environment:
      - CONTAINER=bogtobay
    command: sh -c "git fetch && git checkout devleop-0.7.0 && git pull --rebase && /platform/start-data-container.sh"

  trees:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=trees
      - SITE_KEY=${TREES_KEY}
      - SITE_URL=${TREES_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  trees_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /trees
    environment:
      - CONTAINER=trees
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  snoqualmie:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=snoqualmie
      - SITE_KEY=${SNOQUALMIE_KEY}
      - SITE_URL=${SNOQUALMIE_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  snoqualmie_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /snoqualmie
    environment:
      - CONTAINER=snoqualmie
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  willamette:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=willamette
      - SITE_KEY=${WILLAMETTE_KEY}
      - SITE_URL=${WILLAMETTE_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  willamette_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /willamette
    environment:
      - CONTAINER=willamette
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  lakewashington:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=lakewashington
      - SITE_KEY=${LAKEWASHINGTON_KEY}
      - SITE_URL=${LAKEWASHINGTON_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  lakewashington_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /lakewashington
    environment:
      - CONTAINER=lakewashington
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  waterfront:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=waterfront
      - SITE_KEY=${WATERFRONT_KEY}
      - SITE_URL=${WATERFRONT_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  waterfront_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /waterfront
    environment:
      - CONTAINER=waterfront
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  gtopenspace:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=gtopenspace
      - SITE_KEY=${GTOPENSPACE_KEY}
      - SITE_URL=${GTOPENSPACE_URL}
    restart: always
    command: sh -c "git fetch && git checkout gtopenspace && git pull --rebase && /platform/start.sh"

  gtopenspace_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /gtopenspace
    environment:
      - CONTAINER=gtopenspace
    command: sh -c "git fetch && git checkout gtopenspace && git pull --rebase && /platform/start-data-container.sh"

  watershed:
    image: smartercleanup/platform:release-0.6.4
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=duwamish-watershed
      - SITE_KEY=${DUWAMISH_KEY}
      - SITE_URL=${DUWAMISH_URL}
    restart: always
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start.sh"

  watershed_data:
    image: smartercleanup/platform-data:release-0.6.4
    volumes:
      - /watershed
    environment:
      - CONTAINER=watershed
    command: sh -c "git fetch && git checkout master && git pull --rebase && /platform/start-data-container.sh"

  greenways:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=greenways
      - SITE_KEY=${GREENWAYS_KEY}
      - SITE_URL=${GREENWAYS_URL}
      # Multi-dataset configs:
      - GREENWAYS_DATASET_KEY=${GREENWAYS_KEY}
      - GREENWAYS_SITE_URL=${GREENWAYS_URL}
    restart: always
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"

  greenways_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /greenways
    environment:
      - CONTAINER=greenways
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start-data-container.sh"

  rail:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=rail
      - SITE_KEY=${RAIL_KEY}
      - SITE_URL=${RAIL_URL}
      # Multi-dataset configs:
      - RAIL_DATASET_KEY=${RAIL_KEY}
      - RAIL_SITE_URL=${RAIL_URL}
    restart: always
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"

  rail_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /rail
    environment:
      - CONTAINER=rail
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start-data-container.sh"

  pugetsound:
    image: smartercleanup/platform:release-0.7.1
    environment:
      - DEBUG=False
      - PORT=8000
      - FLAVOR=pugetsound
      - SITE_KEY=${DUWAMISH_KEY}
      - SITE_URL=${DUWAMISH_URL}
      # Multi-dataset configs:
      - DUWAMISH_DATASET_KEY=${DUWAMISH_KEY}
      - DUWAMISH_SITE_URL=${DUWAMISH_URL}
    restart: always
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start.sh"

  pugetsound_data:
    image: smartercleanup/platform-data:release-0.7.1
    volumes:
      - /pugetsound
    environment:
      - CONTAINER=pugetsound
    command: sh -c "git fetch && git checkout develop-0.7.0 && git pull --rebase && /platform/start-data-container.sh"

