marra_data:
  image: smartercleanup/flavors-data
  volumes:
    - /$MARRA_FLAVOR
  environment:
    - FLAVOR=${MARRA_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}

marra:
  image: smartercleanup/flavors
  ports:
    - "${MARRA_PORT}:${MARRA_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${MARRA_PORT}
    - FLAVOR=${MARRA_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}
  restart: always

happytrail_data:
  image: smartercleanup/flavors-data
  volumes:
    - /$HAPPYTRAIL_FLAVOR
  environment:
    - FLAVOR=$HAPPYTRAIL_FLAVOR
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}

happytrail:
  image: smartercleanup/flavors
  ports:
    - "${HAPPYTRAIL_PORT}:${HAPPYTRAIL_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${HAPPYTRAIL_PORT}
    - FLAVOR=${HAPPYTRAIL_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}
  restart: always

trees_data:
  image: smartercleanup/flavors-data
  volumes:
    - /${TREES_FLAVOR}
  environment:
    - FLAVOR=${TREES_FLAVOR}
    - SITE_KEY=${TREES_KEY}
    - SITE_URL=${TREES_URL}

trees:
  image: smartercleanup/flavors
  ports:
    - "${TREES_PORT}:${TREES_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${TREES_PORT}
    - FLAVOR=${TREES_FLAVOR}
    - SITE_KEY=${TREES_KEY}
    - SITE_URL=${TREES_URL}
  restart: always

air_data:
  image: smartercleanup/flavors-data
  volumes:
    - /${AIR_FLAVOR}
  environment:
    - FLAVOR=${AIR_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}

air:
  image: smartercleanup/flavors
  ports:
    - "${AIR_PORT}:${AIR_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${AIR_PORT}
    - FLAVOR=${AIR_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}
  restart: always

nginx_flavors:
  image: smartercleanup/flavors-nginx
  links:
    - "${MARRA_FLAVOR}"
    - "${HAPPYTRAIL_FLAVOR}"
    - "${AIR_FLAVOR}"
    - "${TREES_FLAVOR}"
  volumes_from:
    - "${MARRA_FLAVOR}_data"
    - "${HAPPYTRAIL_FLAVOR}_data"
    - "${AIR_FLAVOR}_data"
    - "${TREES_FLAVOR}_data"
  ports:
    - "80:80"
  volumes:
    - "./marra-happy-air-trees_nginx.conf:/nginx.conf"
  restart: always