willamette_data:
  image: smartercleanup/platform-data:release-0.6.3
  volumes:
    - /$WILLAMETTE_FLAVOR
  environment:
    - FLAVOR=${WILLAMETTE_FLAVOR}
    - SITE_KEY=${WILLAMETTE_KEY}
    - SITE_URL=${WILLAMETTE_URL}
  # command: sh -c "git fetch && git checkout f4847ef7182e && /platform/start-data-container.sh"
  command: sh -c "git fetch && git checkout lukeswart/updates && git pull --rebase && /platform/start-data-container.sh"

willamette:
  image: smartercleanup/platform:release-0.6.3
  ports:
    - "${WILLAMETTE_PORT}:${WILLAMETTE_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${WILLAMETTE_PORT}
    - FLAVOR=${WILLAMETTE_FLAVOR}
    - SITE_KEY=${WILLAMETTE_KEY}
    - SITE_URL=${WILLAMETTE_URL}
    - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always
  command: sh -c "git fetch && git checkout lukeswart/updates && git pull --rebase && /platform/start.sh"

lakewashington_data:
  image: smartercleanup/platform-data:release-0.6.3
  volumes:
    - /$LAKEWASHINGTON_FLAVOR
  environment:
    - FLAVOR=$LAKEWASHINGTON_FLAVOR
    - SITE_KEY=${LAKEWASHINGTON_KEY}
    - SITE_URL=${LAKEWASHINGTON_URL}
  command: sh -c "git fetch && git checkout lukeswart/updates && git pull --rebase && /platform/start-data-container.sh"

lakewashington:
  image: smartercleanup/platform:release-0.6.3
  ports:
    - "${LAKEWASHINGTON_PORT}:${LAKEWASHINGTON_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${LAKEWASHINGTON_PORT}
    - FLAVOR=${LAKEWASHINGTON_FLAVOR}
    - SITE_KEY=${LAKEWASHINGTON_KEY}
    - SITE_URL=${LAKEWASHINGTON_URL}
    # - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always
  command: sh -c "git fetch && git checkout lukeswart/updates && git pull --rebase && /platform/start.sh"

waterfront_data:
  image: smartercleanup/platform-data:release-0.6.3
  volumes:
    - /${WATERFRONT_FLAVOR}
  environment:
    - FLAVOR=${WATERFRONT_FLAVOR}
    - SITE_KEY=${WATERFRONT_KEY}
    - SITE_URL=${WATERFRONT_URL}
  command: sh -c "git fetch && git checkout lukeswart/updates && git pull --rebase && /platform/start-data-container.sh"

waterfront:
  image: smartercleanup/platform:release-0.6.3
  ports:
    - "${WATERFRONT_PORT}:${WATERFRONT_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${WATERFRONT_PORT}
    - FLAVOR=${WATERFRONT_FLAVOR}
    - SITE_KEY=${WATERFRONT_KEY}
    - SITE_URL=${WATERFRONT_URL}
    # - CLICKY_ANALYTICS_ID=${WATERFRONT_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always
  command: sh -c "git fetch && git checkout lukeswart/updates && git pull --rebase && /platform/start.sh"

nginx_platform:
  image: lukeswart/nginx-openresty:release-1.9.7.3
  links:
    - "${WILLAMETTE_FLAVOR}"
    - "${LAKEWASHINGTON_FLAVOR}"
    - "${WATERFRONT_FLAVOR}"
  volumes_from:
    - "${WILLAMETTE_FLAVOR}_data"
    - "${LAKEWASHINGTON_FLAVOR}_data"
    - "${WATERFRONT_FLAVOR}_data"
  ports:
    - "80:80"
  volumes:
    - "./willamette-lakewashington-waterfront_nginx.conf:/nginx.conf"
  restart: always
