willamette_data:
  image: smartercleanup/flavors-data:release-0.6.1
  volumes:
    - /$WILLAMETTE_FLAVOR
  environment:
    - FLAVOR=${WILLAMETTE_FLAVOR}
    - SITE_KEY=${WILLAMETTE_KEY}
    - SITE_URL=${WILLAMETTE_URL}
  command: sh -c "git fetch && git checkout master && git pull --rebase && /duwamish/start-data-container.sh"

willamette:
  image: smartercleanup/flavors:release-0.6.1
  ports:
    - "${WILLAMETTE_PORT}:${WILLAMETTE_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${WILLAMETTE_PORT}
    - FLAVOR=${WILLAMETTE_FLAVOR}
    - SITE_KEY=${WILLAMETTE_KEY}
    - SITE_URL=${WILLAMETTE_URL}
    - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always
  command: sh -c "git fetch && git checkout master && git pull --rebase && /duwamish/start.sh"

happytrail_data:
  image: smartercleanup/flavors-data
  volumes:
    - /$HAPPYTRAIL_FLAVOR
  environment:
    - FLAVOR=$HAPPYTRAIL_FLAVOR
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}

happytrail:
  image: smartercleanup/flavors
  ports:
    - "${HAPPYTRAIL_PORT}:${HAPPYTRAIL_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${HAPPYTRAIL_PORT}
    - FLAVOR=${HAPPYTRAIL_FLAVOR}
    - SITE_KEY=${DUWAMISH_KEY}
    - SITE_URL=${DUWAMISH_URL}
    - CLICKY_ANALYTICS_ID=${DUWAMISH_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always

waterfront_data:
  image: smartercleanup/flavors-data:release-0.6.1
  volumes:
    - /${WATERFRONT_FLAVOR}
  environment:
    - FLAVOR=${WATERFRONT_FLAVOR}
    - SITE_KEY=${WATERFRONT_KEY}
    - SITE_URL=${WATERFRONT_URL}
  command: sh -c "git fetch && git checkout master && git pull --rebase && /duwamish/start-data-container.sh"

waterfront:
  image: smartercleanup/flavors:release-0.6.1
  ports:
    - "${WATERFRONT_PORT}:${WATERFRONT_PORT}"
  environment:
    - DEBUG=${DEBUG}
    - PORT=${WATERFRONT_PORT}
    - FLAVOR=${WATERFRONT_FLAVOR}
    - SITE_KEY=${WATERFRONT_KEY}
    - SITE_URL=${WATERFRONT_URL}
    # - CLICKY_ANALYTICS_ID=${WATERFRONT_CLICKY_ANALYTICS_ID}
    # - MAPBOX_TOKEN=${MAPBOX_TOKEN}
  restart: always
  command: sh -c "git fetch && git checkout master && git pull --rebase && /duwamish/start.sh"

nginx_flavors:
  image: smartercleanup/flavors-nginx
  links:
    - "${WILLAMETTE_FLAVOR}"
    - "${HAPPYTRAIL_FLAVOR}"
    - "${WATERFRONT_FLAVOR}"
  volumes_from:
    - "${WILLAMETTE_FLAVOR}_data"
    - "${HAPPYTRAIL_FLAVOR}_data"
    - "${WATERFRONT_FLAVOR}_data"
  ports:
    - "80:80"
  volumes:
    - "./willamette-happy-waterfront_nginx.conf:/nginx.conf"
  restart: always
