version: '2'
services:
  db:
    image: kartoza/postgis:9.6-2.4
    ports:
      - 35432:5432
    environment:
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=${PGDATABASE}
      - ALLOW_IP_RANGE=${POSTGRES_ALLOW_IP_RANGE}
      - TZ=${TZ}
    restart: always

  ms-api:
    # image: smartercleanup/api:release-0.6.5
    image: mapseed/api-test:6.12
    depends_on:
      - db
    # restart: always
    env_file: ./.env
    volumes:
      - ./set-timezone.sh:/set-timezone.sh
    ports:
      - 8001:8010
    environment:
      - PASS=${POSTGRES_PASS}
      - USERNAME=${POSTGRES_USER}
      - HOST=${POSTGRES_HOST}
      - PORT=${POSTGRES_PORT}
      - TZ=${TZ}
      - SENTRY_DSN=${SENTRY_DSN}
    # command: sh -c "/set-timezone.sh && git fetch && git checkout master && git pull --rebase && /api/start.sh"
    command: sh -c "/set-timezone.sh &&  /api/start.sh"
