version: '2'
services:
  backups:
    image: kartoza/pg-backup:9.4
    hostname: localhost
    volumes:
      - ~/postgres_data/smartercleanup-backups:/backups
    links:
      - postgis:backup-db
    restart: always
    env_file: ./.backups-env
  
  postgis:
    image: kartoza/postgis:9.4-2.1
    volumes:
      - ~/postgres_data/smartercleanup-api:/var/lib/postgresql
      - ./start-postgis.sh:/start-postgis.sh
    ports:
      - 25432:5432
    env_file: ./.postgis-env
    restart: always
    command: sh -c "echo \"host all all 0.0.0.0/0 md5\" >> /etc/postgresql/9.4/main/pg_hba.conf && /start-postgis.sh"
  
  smartercleanup-api:
    image: smartercleanup/api:release-0.6.2
    depends_on:
      - postgis
    restart: always
    env_file: ./.env
    command: sh -c "git fetch && git checkout lukeswart/1.7-dependencies-upgrade && git pull --rebase && /api/start.sh"
  
  nginx-api:
    image: nginx:stable-alpine
    volumes:
      - ./nginx-envsubst.conf:/etc/nginx/nginx.conf
    links:
      - smartercleanup-api
    volumes_from:
      - smartercleanup-api
    ports:
      - 80:80
    restart: always
