version: '3'
services:
  db:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - ~/postgres_data/smartercleanup-api:/var/lib/postgresql
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=${PGDATABASE}
      - ALLOW_IP_RANGE=${POSTGRES_ALLOW_IP_RANGE}
      - TZ=${TZ}
    restart: always
