version: '3'
services:
  smartercleanup-api:
    image: mapseed/api:release-1.5.0
    restart: always
    env_file: ./.env-api
    volumes:
      - ./set-timezone.sh:/set-timezone.sh
      - smartercleanup-api-static:/api/static
    networks:
      - nginx
      - backend
    environment:
      - PASS=${POSTGRES_PASS}
      - USERNAME=${POSTGRES_USER}
      - HOST=${POSTGRES_HOST}
      - PORT=${POSTGRES_PORT}
      - TZ=${TZ}
    command: sh -c "/set-timezone.sh && git fetch && git checkout master && git pull && /api/start.sh"

    # use this to avoid getting errors if we need to run a migration:
    # command: sh -c "touch test.txt && tail -f test.txt"

  letsencrypt:
    image: certbot/certbot
    entrypoint: "sh"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./run-letsencrypt.sh:/run-letsencrypt.sh
    networks:
      - nginx
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm
      - LETSENCRYPT_DOMAINS=${LETSENCRYPT_DOMAINS}
      - LETSENCRYPT_DEBUG_MODE=${LETSENCRYPT_DEBUG_MODE}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    command: "/run-letsencrypt.sh"

  # # For local testing only:
  # nginx:
  #   image: nginx
  #   volumes:
  #   # don't forget to update nginx.conf here, DOMAINS:
  #     - ./nginx-envsubst.conf:/etc/nginx/nginx.conf
  #     - smartercleanup-api:/api
  #   networks:
  #     - nginx
  #   links:
  #     - smartercleanup-api
  #   depends_on:
  #     - smartercleanup-api
  #   ports:
  #     - 80:80
  #   restart: always

  nginx:
    image: modulitos/letsencrypt-nginx:release-1.0.0
    volumes:
      - ./nginx-acme-challenge-envsubst.conf:/etc/nginx/nginx.conf
      - ./nginx-envsubst.conf:/etc/nginx/nginx-secure.conf
      - smartercleanup-api-static:/api/static
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - smartercleanup-api
      - letsencrypt
    depends_on:
      - smartercleanup-api
      - letsencrypt
    networks:
      - nginx
    environment:
      - MY_DOMAIN_NAME=${MY_DOMAIN_NAME}
    ports:
      - 80:80
      - 443:443
    restart: always

  # Our cron container that runs our letsencrypt container, and reloads our nginx container
  letsencrypt-nginx-cron:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt-nginx-cron:/etc/cron.d/letsencrypt-nginx-cron
    # environment:
    #   - TZ=${TZ}
    # TODO: automate timezone script
    command: sh -c "apk add --update tzdata && cp /usr/share/zoneinfo/US/Pacific /etc/localtime && echo 'America/Los_Angeles' > /etc/timezone && date && apk del tzdata && chmod a+x /etc/cron.d/letsencrypt-nginx-cron && touch /var/log/crond.log && crontab /etc/cron.d/letsencrypt-nginx-cron && crond -l 0 -L /var/log/crond.log && echo 'starting nginx-cron' && tail -f /var/log/crond.log"

volumes:
  smartercleanup-api-static:

networks:
  backend:
  nginx:
